name: Flutter Web
on:
  push:
    branches: 
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email kolonel.yudisetiawan@gmail.com
          git config --global user.name coderjava
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/coderjava/coderjava.github.io.git
          git add --all
          git commit -m "Deploy"
          git push origin master
